//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Politico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Constituency
    {
        public Constituency()
        {
            this.MPs = new HashSet<MP>();
        }
    
        public int ID { get; set; }
        public string title { get; set; }
        public Nullable<int> stateID { get; set; }
        public Nullable<int> partyID { get; set; }
    
        public virtual Party Party { get; set; }
        public virtual State State { get; set; }
        public virtual ICollection<MP> MPs { get; set; }
    }
}
