//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Politico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Party
    {
        public Party()
        {
            this.Constituencies = new HashSet<Constituency>();
            this.MPs = new HashSet<MP>();
            this.Questions = new HashSet<Question>();
        }
    
        public int ID { get; set; }
        public string title { get; set; }
        public string abbreviation { get; set; }
        public string image { get; set; }
    
        public virtual ICollection<Constituency> Constituencies { get; set; }
        public virtual ICollection<MP> MPs { get; set; }
        public virtual ICollection<Question> Questions { get; set; }
    }
}
